--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Jviguy/Promises
build-by-default: true
branches:
- master
projects:
  Promises:
    path: ""
    model: virion
    type: library
...
